spring.application.name=Expenses-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/budget
spring.datasource.username=root
spring.datasource.password=tytRib-myksy7-rupmog
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPEN_AI_KEY}
